.pragma library

// Shared chip/tag tokens for Scope (QML side).
var CHIP_RADIUS_MEDIUM = 6
var CHIP_RADIUS_COMPACT = 4

var TAG_CHIP_RADIUS = 6
var TAG_CHIP_HEIGHT_FACTOR = 0.84
var TAG_CHIP_MIN_HEIGHT = 22

var TAG_CHIP_SELECTED_FILL_ALPHA = 0.70
var TAG_CHIP_IDLE_FILL_ALPHA = 0.45
var TAG_CHIP_SELECTED_BORDER_ALPHA = 0.90
var TAG_CHIP_IDLE_BORDER_ALPHA = 0.70

var TAG_FILTER_IDLE_BG_ALPHA = 0.65

